[build]
builder = "nixpacks"
buildCommand = "cd gui && npm install && npm run build"

[deploy]
startCommand = "cd gui && npx serve -s build -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
